from db import get_db_connection
conn=get_db_connection()
cursor=conn.cursor()

cursor.execute('CREATE TABLE IF NOT EXISTS USER(EMPID VARCHAR PRIMARY KEY,USERNAME VARCHAR,PASSWORD BLOB,ROLE VARCHAR,EMAIL VARCHAR,STATUS VARCHAR DEFAULT "Blocked",\
OFFICIAL_MAIL VARCHAR,CONTACT NUMBER)')


cursor.execute('CREATE TABLE IF NOT EXISTS TRAINERS(ID INTEGER PRIMARY KEY AUTOINCREMENT,EMPID VARCHAR,IMAGE BLOB,DATE DATE,LOGIN TIME,LOGOUT TIME,\
               SUBJECT VARCHAR,BATCHCODE VARCHAR,TIMING VARCHAR,TOPIC VARCHAR DEFAULT "NA", FOREIGN KEY (EMPID) REFERENCES USER(EMPID))')

cursor.execute('CREATE TABLE IF NOT EXISTS ATTENDANCE(EMPID VARCHAR,DATE VARCHAR,LOGIN VARCHAR ,LOGOUT VARCHAR,HOURS VARCHAR)')

cursor.execute('CREATE TABLE IF NOT EXISTS SKILLS(ID INTEGER PRIMARY KEY AUTOINCREMENT,EMPID VARCHAR,SKILL VARCHAR,CONCEPT VARCHAR,SUB_CONCEPT VARCHAR,STATUS VARCHAR DEFAULT "on going")')

# cursor.execute('INSERT INTO SKILLS (EMPID) VALUES (?)',("TYP1234",))

cursor.execute('CREATE TABLE IF NOT EXISTS NOTEPAD(EMPID VARCHAR PRIMARY KEY,CONTENT VARCHAR)')

cursor.execute('CREATE TABLE IF NOT EXISTS DEPLOYMENT (EMPID VARCHAR PRIMARY KEY,USERNAME VARCHAR,DEPLOYED VARCHAR DEFAULT "No",LOCATION VARCHAR DEFAULT "NA")')

cursor.execute('CREATE TABLE IF NOT EXISTS TASK(ID INTEGER PRIMARY KEY AUTOINCREMENT,EMPID VARCHAR,TARGET VARCHAR DEFAULT "NA",START DATE,END DATE,PROGRAMS VARCHAR DEFAULT "NA",COMPLETED VARCHAR DEFAULT "False")')


cursor.execute('DELETE FROM ATTENDANCE WHERE EMPID="TYP2511"')
conn.commit()


